-- SQL-файл для практичної роботи:
-- Автоматизована інформаційна система "Місця проведення дозвілля громадян"
-- Вставити у Supabase: SQL Editor -> New query -> вставити код -> Run.

-- 1. Очищення старих таблиць, якщо вони вже були створені
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.object_status CASCADE;
DROP TABLE IF EXISTS public.objects CASCADE;
DROP TABLE IF EXISTS public.owners CASCADE;

-- 2. Таблиця власників
CREATE TABLE public.owners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type TEXT NOT NULL CHECK (owner_type IN ('Фізична особа', 'Юридична особа')),
  company_name TEXT,
  director_name TEXT,
  phone TEXT NOT NULL
);

-- 3. Таблиця об'єктів дозвілля
CREATE TABLE public.objects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_name TEXT NOT NULL,
  object_type TEXT NOT NULL,
  address TEXT NOT NULL,
  seats INTEGER NOT NULL CHECK (seats >= 0),
  opening_date DATE NOT NULL,
  owner_id BIGINT NOT NULL REFERENCES public.owners(id) ON DELETE RESTRICT
);

-- 4. Таблиця відвідуваності
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id BIGINT NOT NULL REFERENCES public.objects(id) ON DELETE CASCADE,
  visit_date DATE NOT NULL,
  visitors_count INTEGER NOT NULL CHECK (visitors_count >= 0)
);

-- 5. Таблиця заходів
CREATE TABLE public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id BIGINT NOT NULL REFERENCES public.objects(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_date DATE NOT NULL
);

-- 6. Таблиця статусів роботи об'єктів
-- Якщо end_date = NULL, об'єкт працює без вказаної дати закриття.
CREATE TABLE public.object_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id BIGINT NOT NULL REFERENCES public.objects(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  CHECK (end_date IS NULL OR end_date >= start_date)
);

-- 7. Індекси для швидшого пошуку
CREATE INDEX idx_objects_type ON public.objects(object_type);
CREATE INDEX idx_objects_owner_id ON public.objects(owner_id);
CREATE INDEX idx_events_date ON public.events(event_date);
CREATE INDEX idx_events_object_id ON public.events(object_id);
CREATE INDEX idx_status_dates ON public.object_status(start_date, end_date);
CREATE INDEX idx_status_object_id ON public.object_status(object_id);
CREATE INDEX idx_attendance_object_date ON public.attendance(object_id, visit_date);

-- 8. Тестові дані: власники
INSERT INTO public.owners (owner_type, company_name, director_name, phone) VALUES
('Юридична особа', 'ТОВ "Міський простір"', 'Ковальчук Андрій Ігорович', '+380671112233'),
('Юридична особа', 'ПП "АртЛайф"', 'Мельник Олена Петрівна', '+380672224455'),
('Фізична особа', NULL, 'Шевченко Максим Романович', '+380503334455'),
('Юридична особа', 'ТОВ "Спорт Енергія"', 'Гнатюк Ірина Василівна', '+380934445566'),
('Фізична особа', NULL, 'Бойко Назар Сергійович', '+380665556677'),
('Юридична особа', 'ТОВ "КіноСвіт"', 'Демчук Марія Олегівна', '+380687778899');

-- 9. Тестові дані: об'єкти дозвілля
INSERT INTO public.objects (object_name, object_type, address, seats, opening_date, owner_id) VALUES
('Кінотеатр "Прем'єра"', 'Кінотеатр', 'вул. Центральна, 12', 180, '2018-04-12', 6),
('Спортзал "Атлант"', 'Спортзал', 'вул. Спортивна, 4', 70, '2020-01-20', 4),
('Більярдний клуб "8 Куля"', 'Більярдний клуб', 'просп. Молоді, 18', 45, '2019-09-03', 3),
('Танцювальний зал "Ритм"', 'Танцзал', 'вул. Шевченка, 22', 120, '2021-05-15', 2),
('Концертний майданчик "Open Air"', 'Концертний майданчик', 'парк ім. Франка', 600, '2022-06-01', 1),
('Клуб настільних ігор "Dice"', 'Клуб', 'вул. Грушевського, 9', 35, '2023-02-10', 5),
('Молодіжний центр "Start"', 'Молодіжний центр', 'вул. Незалежності, 33', 150, '2020-10-01', 1),
('Арт-студія "Колір"', 'Арт-студія', 'вул. Лесі Українки, 7', 40, '2021-11-11', 2),
('Літній кінотеатр "Парк"', 'Кінотеатр', 'міський парк, зона 2', 220, '2024-06-01', 6),
('Сезонний роледром "Drive"', 'Роледром', 'вул. Промислова, 15', 90, '2023-07-05', 4);

-- 10. Тестові дані: статуси роботи об'єктів
-- Більшість об'єктів активні на поточну дату.
INSERT INTO public.object_status (object_id, start_date, end_date) VALUES
(1, current_date - 120, NULL),
(2, current_date - 200, NULL),
(3, current_date - 180, NULL),
(4, current_date - 90, NULL),
(5, current_date - 30, current_date + 90),
(6, current_date - 250, NULL),
(7, current_date - 150, NULL),
(8, current_date - 75, NULL),
(9, current_date - 10, current_date + 80),
(10, current_date - 300, current_date - 5);

-- 11. Тестові дані: відвідуваність
INSERT INTO public.attendance (object_id, visit_date, visitors_count) VALUES
(1, current_date - 6, 130),
(1, current_date - 5, 142),
(2, current_date - 6, 55),
(2, current_date - 4, 61),
(3, current_date - 3, 29),
(4, current_date - 2, 87),
(5, current_date - 2, 320),
(6, current_date - 1, 24),
(7, current_date - 1, 96),
(8, current_date - 1, 31),
(9, current_date, 120);

-- 12. Тестові дані: заходи
-- Дати створені відносно current_date, тому запит "на найближчі 14 днів" буде працювати в будь-який день.
INSERT INTO public.events (object_id, event_name, event_type, event_date) VALUES
(1, 'Прем'єра українського фільму', 'Кінопоказ', current_date + 1),
(2, 'Відкрите тренування з боксу', 'Спортивний захід', current_date + 2),
(4, 'Вечір сучасних танців', 'Танцювальний захід', current_date + 4),
(5, 'Міський концерт молодих гуртів', 'Концерт', current_date + 6),
(6, 'Турнір з настільних ігор', 'Турнір', current_date + 8),
(7, 'Зустріч молодіжних ініціатив', 'Зустріч', current_date + 10),
(8, 'Майстер-клас з живопису', 'Майстер-клас', current_date + 13),
(9, 'Вечірній кінопоказ просто неба', 'Кінопоказ', current_date + 14),
(3, 'Чемпіонат з більярду', 'Змагання', current_date + 16),
(5, 'Фестиваль вуличної музики', 'Фестиваль', current_date - 2);

-- 13. Увімкнення Row Level Security
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.object_status ENABLE ROW LEVEL SECURITY;

-- 14. Видалення старих політик, якщо SQL запускається повторно
DROP POLICY IF EXISTS "Allow public read owners" ON public.owners;
DROP POLICY IF EXISTS "Allow public read objects" ON public.objects;
DROP POLICY IF EXISTS "Allow public read attendance" ON public.attendance;
DROP POLICY IF EXISTS "Allow public read events" ON public.events;
DROP POLICY IF EXISTS "Allow public read object_status" ON public.object_status;

-- 15. Політики доступу: сайт може тільки читати дані через anon key
CREATE POLICY "Allow public read owners"
ON public.owners
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow public read objects"
ON public.objects
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow public read attendance"
ON public.attendance
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow public read events"
ON public.events
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow public read object_status"
ON public.object_status
FOR SELECT
TO anon
USING (true);
